### ISSUE TITLE
【質問】mtk3_bsp2のシリアル通信のデバイスドライバのサポートについて

### ISSUE THREAD

**Issue by grace2riku** [tron-forum/mtk3_bsp2#8]
掲題の件で質問です。

mtk3_bsp2（ターゲットボードはstm32h723）でシリアル通信のデバイスドライバを使いたいと考えています。
mtk3_bspでシリアル通信のデバイスドライバはサポートされていたように見えますが、mtk3_bsp2だとサポートされていないようです。

mtk3_bsp2でシリアル通信のデバイスドライバがサポートされていないのは何か理由があるのでしょうか?

mtk3_bspのシリアル通信のデバイスドライバをmtk3_bsp2に移植できないか考えています。
mtk3_bsp2でシリアル通信のデバイスドライバがサポートされていないのは技術的に難しい課題があったから、などであれば事前に知りたいと思い、質問させていただきました。

**Comment by ytoyo-iniad** [comment]
BSP2でシリアル通信のデバイスドライバの対応に技術的な問題はございません。
STM32H723であれば、BSPのドライバをBSP2に持ってきて使用することも可能です。その際が端子などのH/W初期化は必要となりますのでご注意ください。

BSP2では全マイコンボード共通で、ドライバはHAL使用のサンプルとしてA/DCとI2Cを提供し、UARTはデバッグ用通信のみとしております。これはセンサーなど外部ペリフェラルの接続にはA/DCとI2Cのニーズが高いのではという想定です。

**Comment by grace2riku** [comment]
@ytoyo-iniad ご回答ありがとうございます。

>BSP2でシリアル通信のデバイスドライバの対応に技術的な問題はございません。

技術的な問題ないこと、承知しました。

>STM32H723であれば、BSPのドライバをBSP2に持ってきて使用することも可能です。
>その際が端子などのH/W初期化は必要となりますのでご注意ください。

ご丁寧にありがとうございます。承知しました。

>BSP2では全マイコンボード共通で、ドライバはHAL使用のサンプルとしてA/DCとI2Cを提供し、
>UARTはデバッグ用通信のみとしております。これはセンサーなど外部ペリフェラルの接続には
>A/DCとI2Cのニーズが高いのではという想定です。

背景理解しました。ありがとうございます。

個人的にシリアル通信の割込みを使った構造を試してみたく、その前にBSP→BSP2移植の際に課題などあるのかと思ったのでご質問させていただきました。
